import pandas as pd
from textwrap import wrap
import mysql.connector as mysql
import streamlit as st
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import io

def pdfgen(res):
    buf=io.BytesIO()
    c=canvas.Canvas(buf,pagesize=A4)
    w,h=A4
    y=h-50
    c.setFont("Helvetica",16)
    c.drawString(50, y, f"AI Powered Roadmap Generator")
    y -= 50
    c.setFont("Helvetica-Oblique",12)
    c.drawString(50, y, f"Course: {res['Course']}")
    y -= 25
    c.drawString(50, y, f"Goal: {res['Goal']}")
    y -= 25
    c.drawString(50, y, f"Level: {res['Path_Level']}")
    y -= 25
    c.drawString(50, y, f"Duration: {res['Duration_weeks']} weeks")
    y -= 25
    c.drawString(50, y, f"Outcome: {res['Outcome']}")
    y -= 30
    textobject = c.beginText(50, y)
    textobject.setFont("Helvetica", 12)
    textobject.setLeading(14)

    wrapped = wrap(f"Phase Details: {res['Phase_Details']}", 90)
    textobject.textLines(wrapped)
    c.drawText(textobject)
    y -= 40
    c.setFont("Courier", 10)
    c.drawCentredString(w/2,30, "Generated by AI Powered Road Map Finder")

    c.showPage()
    c.save()
    buf.seek(0)
    return buf

st.title("AI Powered Road Map Generator")


sql=mysql.connect(host="localhost",user="root",password="hpkpro", database="roadmap")
cur=sql.cursor()
print("Database Connected")

data=pd.read_excel(r"C:\data\projects\ai_roadmap\learning_roadmap_with_phases.xlsx")

vectorizer=TfidfVectorizer(stop_words="english")

print("Intilized successfully")

data["x"]=data["Goal"]+" "+data["Course"]+" "+data["Outcome"]+" "+data["Current_Skills"]+" "+data["Interests"]

mat=vectorizer.fit_transform(data["x"])


user=st.text_input("Enter What you want to learn/become:")
skills=st.text_input("Enter your skills/Interest:")

skill=vectorizer.transform([skills])
goal=vectorizer.transform([user])

res=(0.6*goal)+(0.4*skill)


sim=cosine_similarity(res,mat)
l=sim.argsort()[0][::-1]
index=0

col=["Course","Goal","Path_Level","Duration_weeks","Outcome","Phase_Details"]
if(user):
    if "index" not in st.session_state:
        st.session_state.index = index
    st.write("\n=== Based on your skills and goal I suggest you ===\n")
    if st.session_state.index >= len(l):
        st.write("Sorry, but no more suggestions available.")
        st.write("Thank you for using this model")
        st.stop()

    result = data.iloc[l[st.session_state.index]]

    with st.container():
        st.markdown("### 🎯 Recommended Roadmap")
        st.markdown(
            f"""
            **📘 Course:** {result["Course"]}  
            **🎯 Goal:** {result["Goal"]}  
            **📈 Level:** {result["Path_Level"]}  
            **⏳ Duration:** {result["Duration_weeks"]} weeks  
            **✅ Outcome:** {result["Outcome"]}
            
            **🛣  Step-by-Step Learning Path:** {result["Phase_Details"]}
            """
        )
    st.write("")

    if st.button("Suggest another"):
        st.session_state.index += 1
        st.rerun()
    pdf=pdfgen(result)

    st.download_button(
        label="📥 Download Roadmap as PDF",
        data=pdf,
        file_name="recommended_roadmap.pdf",
        mime="application/pdf"
        )

with st.sidebar:
    st.subheader("📝 Leave Feedback")
    with st.expander("📊 Give Feedback"):
        with st.form("✏️ feedback_form"):
            name = st.text_input("🧑 Your name")
            rating = st.slider("⭐ Rating", 0, 10, 5)
            feedback = st.text_area("💬 Comments")

            submit = st.form_submit_button("Submit Feedback")

            if(submit):
               q=f"insert into FeedBack(Name, Suggested_Course_Id, Suggested_Course, Rating, feedback) values(%s,%s,%s,%s,%s);"
               v=(name,int(result["ID"]),result["Course"],rating,feedback)
               cur.execute(q,v)
               sql.commit()
               st.success("Thank you for your FeedBack")
